### ISSUE TITLE
Getting "Invalid PNG buffer" for a valid image

### ISSUE THREAD

**Issue by IonicaBizau** [EyalAr/lwip#229]
The image is valid, but `lwip` can't understand it. Where should we start debugging?

**Comment by IonicaBizau** [comment]
:bell: @EyalAr

**Comment by EyalAr** [comment]
Can you please upload the original image?

Otherwise I'd try to open this image with libpng's example program.

**Comment by IonicaBizau** [comment]
@EyalAr I uploaded it [here](https://www.dropbox.com/s/u1ob4nvczh55x3y/octocat.png?dl=0) (note I will remove it since the issue is fixed or obsolete).

**Comment by gabox8888** [comment]
This is still happening, any idea what the fix is/was? what to do?

**Comment by IonicaBizau** [comment]
@gabox8888 I think it's still an issue...
@EyalAr :bell:

**Comment by IonicaBizau** [comment]
@EyalAr :bell: Please....!

**Comment by acoyfellow** [comment]
I can confirm this is happening with perfectly valid .PNG's.

**Comment by IonicaBizau** [comment]
Just a little update: in my case, it was a JPG file, with the `png` extension.

@acoyfellow Double check if your image is really a PNG file or it's just a valid image but with a wrong extension. Some programs may display it correctly, but when parsing it you must specify the type.

**Comment by acoyfellow** [comment]
@IonicaBizau thanks for the tip. I did realize that was happening for some cases. 

But I still get this error with iOS generated .PNG files from screenshots, when uploading files via fetch (using React Native). 

A workaround I suppose would be to catch the "Invalid PNG buffer", and cycle through alternative extensions to see if lwip can read it.

**Comment by ChristianRich** [comment]
I can confirm that changing the affected PNG's file extension to jpg indeed fixes the problem.

**Comment by IonicaBizau** [comment]
But still, `lwip` should be smart enough to detect the image buffer type (and not by using the extension).

**Comment by ChristianRich** [comment]
@IonicaBizau That would certainly be a nice feature, that the type is determined not by the file extension but the header. Still I find the workaround perfectly acceptable. As long as you can intercept the error and handle it I'm fine.
